ALTER TABLE student.gamification_stats
ADD COLUMN IF NOT EXISTS daily_abandon_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_abandon_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS abandon_blocked_until TIMESTAMP WITH TIME ZONE;

ALTER TABLE student.duels
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

